openapi: "3.0.0"
info:
  version: 1.0.0
  title: Customer API
paths:
  /customers:
    get:
      summary: List customers
      operationId: listCustomers
      responses:
        '200':
          description: A list of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"

components:
    schemas:
      Customer:
        type: object
        properties:
          name:
            type: string
